[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
zkonnect = "E8kA7XjYkKYbXVFm8BWr3NEpSZMKrotQhpf32YLg3mQ6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
